# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: mateo.olarte9@gmail.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://mateoolarte.com"
twitter_username: mateo_olarte
github_username:  mateoolarte
facebook_username:  mateoolarte
email_username:  mateo.olarte8@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
