# Site settings
title: Mateo Olarte
job: Frontend Developer
header-img: img/home-bg.jpg
email: mateo.olarte9@gmail.com
copyright_name: Mateo Olarte
description: "Blog personal"
baseurl: ""
url: "http://mateoolarte.com"
twitter_username: mateo_olarte
github_username: mateoolarte
linkedin_username: mateoolarte
email_username: mateo.olarte8@gmail.com

# Google Analytics
google_tracking_id: UA-60678906-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
